language: swift
osx_image: xcode10.2
install:
    - npm install -g danger/tap/danger-swift
script:
    - danger-swift ci
    - xcodebuild test -project DADependencyInjection.xcodeproj -scheme DADependencyInjection -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2'
after_success:
    - bash <(curl -s https://codecov.io/bash)